### ISSUE TITLE
NA en las variables "province" y "ccaa"

### ISSUE THREAD

**Issue by numeroteca** [kifirifis/asturiasescovid19data#1]
En https://github.com/kifirifis/asturiasescovid19data/blob/main/data/output.csv aparece NA en las variables "province" y "ccaa" ¿podrías poner que esten rellenas aunque los datos estén vacíos?

Otra cuestión: ¿cómo decides que está vacio el dato si es por scraping?

**Comment by kifirifis** [comment]
El dato está vacío cuando no se produjo ningún cambio en la página; Esto suele ocurrir sábado y domingo. Cuando esto pasa entonces únicamente se registra la fecha en la que no hubo datos aunque efectivamente debería registrarse además de la fecha también "province" y "caaa".  Relleno "province" y "ccaa" hoy @numeroteca.

**Comment by kifirifis** [comment]
@numeroteca Fixed: sha 818bf8f
